stages:
  - build
  - deploy

include:
  - project: 'occloxium-webdev/k8s'
    ref: master
    file: '/ci/.gitlab-ci.yml'

build:
  stage: build
  image: docker:latest
  script:
    - echo "$CI_JOB_TOKEN" | docker login registry.git.rwth-aachen.de --username gitlab-ci-token --password-stdin 
    - docker build -t registry.git.rwth-aachen.de/occloxium-webdev/pizzabot/backend ./server
    - docker build -t registry.git.rwth-aachen.de/occloxium-webdev/pizzabot/frontend ./client
    - docker push registry.git.rwth-aachen.de/occloxium-webdev/pizzabot/frontend:latest 
    - docker push registry.git.rwth-aachen.de/occloxium-webdev/pizzabot/backend:latest
  tags:
    - occloxium-docker

deploy:
  stage: deploy
  extends: .kubectl
  script:
    - kubectl rollout restart deployment/pizzabot